### ISSUE TITLE
/add quote "Sending command..." lingers after first use

### ISSUE THREAD

**Issue by SafaiaArt** [Leyla-Labs/Leyla.Bot#31]
As title says, this stays behind after executing the /add quote command for the first time:

<img width="283" alt="Screenshot 2022-11-22 at 15 14 24" src="https://user-images.githubusercontent.com/116829723/203336517-41cfb83b-6532-4140-9bb3-6a3ffd2c4433.png">

This disappears after restarting Discord client, pops up again when the command is used. The command itself functions as expected with no issues.

**Comment by Tawmy** [comment]
I have no idea why this is happening, each case is handled exactly the same in code. The message should disappear as soon as the modal opens. I've opened a thread on the DSharpPlus server and will update this issue later.

**Comment by Tawmy** [comment]
Looks like this is a Discord issue that'll hopefully be resolved soon.
