### ISSUE TITLE
Shorten validity of character claim

### ISSUE THREAD

**Issue by Tawmy** [Leyla-Labs/Leyla.Bot#35]
XIVAPI has an awfully long caching time - so long that after getting a full night's sleep, character data may still not be refreshed. This was a problem when trying to confirm character claims. The command was first built on the assumption caching updates might take hours, so users would often have to try again the next day.

The validity of claims was therefore set to be three days. Since the bot now directly parses the Lodestone page to verify claims, it works immediately. The validity can therefore be drastically reduced - one hour should be fine.

- [x] Adjust expiry date
- [x] Adjust strings mentioning the longer expiry

**Comment by Tawmy** [comment]
QA notes: Please test expiry in real world scenario:

- [ ] Create claim with user 1
- [ ] Try to create same claim with user 2 -> should show error with adjusted string (1 hour, not 3 days)
- [ ] Try to create same claim with user 2 after an hour -> should let you create the claim
- [ ] Try to create same claim with user 1 -> should show error again

**Comment by SafaiaArt** [comment]
- [x]   Create claim with user 1
- [x]   Try to create same claim with user 2 -> should show error with adjusted string (1 hour, not 3 days)
- [x]   Try to create same claim with user 2 after an hour -> should let you create the claim
- [x]   Try to create same claim with user 1 -> should show error again

Everything works and correctly shows the adjusted string.

**Comment by Tawmy** [comment]
Sweet, thank you for the QA.
