### ISSUE TITLE
Show link to Lodestone profile when bot posts character sheet

### ISSUE THREAD

**Issue by Tawmy** [Leyla-Labs/Leyla.Bot#37]
Add link in same fashion as AniList commands

- [x] Character show
- [x] Character list

**Comment by SafaiaArt** [comment]
Both of these work as expected, with links correctly redirecting to their respective characters.

One random character I looked up did not have a link under their profile. Very new character (Chibi-cloud Strife on Moogle [Chaos]).

![Image](https://user-images.githubusercontent.com/116829723/203395983-4a99efda-2626-4e0c-867d-b584963b9ef8.png)

**Comment by SafaiaArt** [comment]
Fixed! Looked up multiple characters with no issues 👍
