### ISSUE TITLE
"No claimed character" needs to be ephemeral

### ISSUE THREAD

**Issue by Tawmy** [Leyla-Labs/Leyla.Bot#39]
Right now, the message is posted publicly. This is inconsistent with other bot behaviour, from which users would assume they'd be told in private.

<img width="480" alt="Screenshot 2022-11-22 at 18 16 41" src="https://user-images.githubusercontent.com/22292560/203379260-ace8f7e5-08ef-44df-a2b9-5bc5d51ea716.png">

**Comment by SafaiaArt** [comment]
The message is now private.
<img width="615" alt="Screenshot 2022-11-22 at 20 36 52" src="https://user-images.githubusercontent.com/116829723/203405617-3fda1a26-3320-422c-9e8b-959586de6e0c.png">
