### ISSUE TITLE
Cannot change only description of self-assign menu

### ISSUE THREAD

**Issue by Tawmy** [Leyla-Labs/Leyla.Bot#49]
When running /menu rename and changing only the description, an error "A self-assign menu with that name already exists" shows up.

**Comment by Tawmy** [comment]
Logic has been adjusted to also check if the PK of the entry is different.

**Comment by SafaiaArt** [comment]
I was able to successfully change only the description with no errors 👍

**Comment by Tawmy** [comment]
Thank you for the QA!
