### ISSUE TITLE
Commands: Claiming character and character data shorthand

### ISSUE THREAD

**Issue by Tawmy** [Leyla-Labs/Leyla.Bot#5]
Once #4 is implemented, an additional command to claim a character will be implemented.

A way to verify ownership of a character will be necessary. Some websites have the user add a GUID or similar to their Lodestone profile. Since the bot is using XIVAPI, this may not be feasible due to caching, that will need to be checked.

**AC:**

Claim command:
- [x] User can search for character using character name and world
- [x] Bot will show dropdown with selection if multiple characters found, otherwise this will be skipped
- [x] Bot shows user (and only this user) verification code

Verify claim command:
- [ ] Simple command without parameters to verify claims
- [ ] Iterate all open requests
- [x] If successfully verified, save
- [ ] If not successfully verified, ask if user wants to delete request

Character data shorthand
- [x] Simple command without parameters to show character data
- [x] If multiple characters have been claimed, show dropdown with character selection
- [x] Character selection dropdown needs to show both character name and world

**Comment by Tawmy** [comment]
Verify claim command has been implemented differently due to limitations in DSharpPlus.

Claim command can now be reused to verify claims. The same character search shows up and all six possible scenarios are handled:

1. Claim did not exist yet, now newly created
2. Claim already exists for this character, but user has not put it on their Lodestone profile yet
3. Claim already exists and has been found on their Lodestone profile -> now confirmed
4. Claim already exists, but has previously been confirmed -> no action necessary
5. Claim already exists for different user -> need to wait for three day expiry
6. Claim already exists for different user, but has been confirmed -> character belongs to someone else, block

Claims stay open forever, but they expire after three days. After those three days, if a different user creates a claim for that character, the expired unconfirmed claim is silently deleted and a new one created for this other user.

**Comment by Tawmy** [comment]
Notes for QA:

All six scenarios for the claim command need to be tested.

Being able to overwrite a claim after three days can be tested by creating the claim with user 1, then changing the date in the database to be in the past, then creating a claim for the same character with user 2.

The Me command also handles various scenarios:

1. No claims at all
2. Only unconfirmed claims
3. One character confirmed -> shows directly
4. Multiple characters confirmed -> show selection -> show character correctly after selection

**Comment by Tawmy** [comment]
I'll have to update your database so lmk whenever you start testing @SafaiaArt

**Comment by Tawmy** [comment]
Thank you for the QA! I've found the cause of the issue and have implemented a fix, would you mind testing if it's fixed for you please?

**Comment by SafaiaArt** [comment]
The fix works. A new code is now generated every time, I was able to verify this by deleting database entries and trying the command again with my own character and yours.

**Comment by Tawmy** [comment]
Sweet, thank you for re-checking.
